# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Demo App Workflow

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy Demo App
    runs-on: ubuntu-latest
    env:
        GAMMA_AWS_ACCESS_KEY_ID: ${{secrets.GAMMA_AWS_ACCESS_KEY}}
        GAMMA_AWS_SECRET_ACCESS_KEY: ${{secrets.GAMMA_AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
        AWS_DEFAULT_OUTPUT: text
        GAMMA_CHIME_ENDPOINT: ${{secrets.GAMMA_CHIME_ENDPOINT}}
        DEVO_AWS_ACCESS_KEY_ID: ${{secrets.DEVO_AWS_ACCESS_KEY_ID}}
        DEVO_AWS_SECRET_ACCESS_KEY: ${{secrets.DEVO_AWS_SECRET_ACCESS_KEY}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install SAM CLI
        run: script/github-action-awscli-installation
      - name: Deploy the Serverless Demo App
        run: script/deploy-canary-demo
